spring:
  profiles:
    active: dev
---
spring:
  profiles: dev
  application:
    name: spring-cloud-config-4403-dev
---
spring:
  profiles: prod
  application:
    name: spring-cloud-config-4403-prod
