spring:
  profiles:
    active: dev

---
#配置连接数据库
spring:
  profiles: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://192.168.25.131:3306/cloud?characterEncoding=utf-8
  application:
    name: spring-cloud-provider


#整合mybatis
mybatis:
  config-location: classpath:/mybatis/conf/mybatisConfig.xml
  mapper-locations: classpath:/mybatis/mapper/*.xml
logging:
  level:
    com.yuan.springcloud.mapper: debug
#配置eureka客户端
eureka:
  client:
    service-url:
#      defaultZone: http://localhost:7001/eureka/ #eureka的服务地址
      defaultZone: http://localhost:4404/eureka #eureka的服务地址
  instance:
    prefer-ip-address: true
    instance-id: spring-cloud-provider-8081 #定义服务的名称

#endpoints:
#  info:
#    enabled: true
info:
    username: yuanyifei
    password: 123456
    gander: 男
    description: 使用springcloud config来统一管理微服务的配置文件
